# Generated by Django 4.2.6 on 2023-10-12 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='links',
            field=models.URLField(default='#'),
        ),
    ]
