# Generated by Django 4.2.6 on 2023-10-12 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='links',
            field=models.URLField(blank=True, null=True),
        ),
    ]
