# Generated by Django 4.2.6 on 2023-10-13 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_add_about_edu_model_others'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Others',
            new_name='AboutOthers',
        ),
        migrations.RenameModel(
            old_name='Skills',
            new_name='AboutSkills',
        ),
    ]
