# Generated by Django 4.2.6 on 2023-10-13 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_add_about_edu_model_others'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abouteducation',
            name='relevant_courses',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='aboutexperience',
            name='job_description',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='aboutexperience',
            name='job_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='links',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
