# Generated by Django 4.2.6 on 2023-10-13 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_add_about_edu_model_method_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutexperience',
            name='job_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aboutskills',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
